"""Initial migration

Revision ID: ddfb44df83d8
Revises: 
Create Date: 2025-03-30 18:28:33.975367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfb44df83d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    op.add_column('challenges', sa.Column('level_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'challenges', 'levels', ['level_id'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.drop_column('users', 'completed_challenges')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('completed_challenges', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_column('challenges', 'level_id')
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    # ### end Alembic commands ###
